### ISSUE TITLE
Datatables auto heigh to fill the screen

### ISSUE THREAD

**Issue by Neolium** [Neolium/consult_panel#20]
Mettre les datatables à la hauteur maximum pour l'écran courant

**Comment by QuentinBross** [comment]
?? C'est fait

**Comment by Neolium** [comment]
[
<img width="1440" alt="capture d ecran 2016-06-28 a 22 38 58" src="https://cloud.githubusercontent.com/assets/12201034/16431496/27c6cd3e-3d81-11e6-8c00-bec65f1c2993.png">
](url)

**Comment by QuentinBross** [comment]
Il n'y a que 6 row à afficher, je ne vais pas faire une box blanche plus grande que nécessaire. Donc c'est fait.

**Comment by Neolium** [comment]
<img width="1201" alt="capture d ecran 2016-06-28 a 22 44 27" src="https://cloud.githubusercontent.com/assets/12201034/16431664/eba19978-3d81-11e6-97a1-2a93ed562037.png">

**Comment by Neolium** [comment]
<img width="1202" alt="capture d ecran 2016-06-28 a 22 45 07" src="https://cloud.githubusercontent.com/assets/12201034/16431677/fb9011ca-3d81-11e6-91ed-184fdccc37e0.png">

**Comment by Neolium** [comment]
Sur le dernier on voit bien que la box est de taille fixe : scroll + bande grise en bas

**Comment by QuentinBross** [comment]
Tu a gulp ? Sinon il y a des soucis quelque part, c'est fonctionnel chez moi

**Comment by Neolium** [comment]
<img width="774" alt="capture d ecran 2016-06-28 a 22 48 22" src="https://cloud.githubusercontent.com/assets/12201034/16431800/78731a0c-3d82-11e6-8699-c08575418c4b.png">

**Comment by QuentinBross** [comment]
Ha, il manque des fichiers less je crois
