### ISSUE TITLE
Bug with unique_linker

### ISSUE THREAD

**Issue by matthieuberger** [Neolium/consult_panel#29]
<img width="1271" alt="capture d ecran 2016-08-23 a 14 51 04" src="https://cloud.githubusercontent.com/assets/15636583/17892343/182f1480-6941-11e6-9b22-7f4794efe60a.png">

**Comment by QuentinBrosse** [comment]
@matthieuberger Alors je viens de regarder, c'est tous à fait normale, tu passe "16" en paramètre au lieux de passer un tableau (qui sera convertis en JSON, puis stocké dans la BDD). Ca voir dans la BDD la différence entre mon exemple "consult_panel.models/DebugValidateEmail/valid" et ta validation de mail.

Regarde bien ici : https://github.com/Neolium/consult_panel/wiki/Unique-Linker#cr%C3%A9ation-du-lien-unique (`params = {"id": debug_validate_email.id}`et non `params = debug_validate_email.id`)

Je peux te laisser fix tous seul ? (Tu supprimeras bien l'entrée `745974b073624f0b894a40dda47ace2d` dans la table `unique_linker_unique`)
